version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-rdkitjs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cj8qdidyv95r"
s3_prefix = "sam-rdkitjs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=405835607149.dkr.ecr.us-east-1.amazonaws.com/tests"]
